apiVersion: apps/v1
kind: Deployment
metadata:
  name: doings-deployment
  labels:
    app: doings-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doings-app
  template:
    metadata:
      labels:
        app: doings-app
    spec:
      containers:
      - name: doings-container  
        image: 456618395112.dkr.ecr.us-east-1.amazonaws.com/doingsecr:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: doings-service
spec:
  selector:
    app: doings-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
